### PR TITLE
Updated Dir to use Github at WowAce

### PR DESCRIPTION
**Pull request by gOOvER**
- Added pkgmeta.yaml

- added acelocale nfor using translation System from wowace

These changes are all basic and should work :)

### CODE REVIEW

**Comment by Stanzilla** [comment]
urm nope, no idea what you did there but you deleted unrelated files and did some changes that are not needed. we already have a .pkgmeta file, that means we don't need pkgmeta.yml

**Comment by gOOvER** [comment]
That was as an example  when Project will host at curseforge and when Github it's used for Code. ;)

pkgmeta.yml is needed for wowace. .pkgmeta is not longer used bei WoWAce ;)

This PR was only to show, what changes are needed ;)

**Comment by Stanzilla** [comment]
`pkgmeta.yml is needed for wowace. .pkgmeta is not longer used and supported by WoWAce ;)` 

that is not true, sorry.

**Comment by gOOvER** [comment]
https://www.curseforge.com/docs/packaging

**Comment by Stanzilla** [comment]
Yeah that is missing information that both file names work. 

@Torhal fix please

**Comment by gOOvER** [comment]
Filename Maybe, but content??

I had problems which external Libs with old way ;) Need to use new way

**Comment by Stanzilla** [comment]
Do you want to do the locale changes as a separate PR?

**Comment by gOOvER** [comment]
i can do this.... :) I revert rest in my fork and send only the Locale

**Comment by Torhal** [comment]
```I had problems which external Libs with old way ;) Need to use new way```

That doesn't make any sense - the packager looks for a pkgmeta.yaml and if one isn't found it looks for .pkgmeta. No matter which is found, the same processing code is ran on the file. The new file name was introduced simply to clear up what it is (YAML) and make its creation easier on Windows.

**Pull request closed without merging**
