### PR TITLE
Emissary Quests Category

### PR DESCRIPTION
**Pull request by dsabecky**
Visual fix.

### CODE REVIEW

**Comment by dsabecky** [comment]
Any word on this being good or not?

**Comment by Stanzilla** [comment]
Sorry, will take a look when at home on the weekend!

**Comment by SacredDuckwhale** [comment]
Is there any good reason why you changed the formatting? It makes it much harder to read and understand what's going on, especially for a small change such as this.
Also, the commit title and message isn't clear on what is being changed.

That's all the technicalities I could find :)

**Comment by dsabecky** [comment]
It’s formatted the same as the other two categories are (raids and dungeons).

**Comment by dsabecky** [comment]
It’s to bring uniformity to the addon instead of having some things formatted one way and some things formatted a different way.

**Comment by Stanzilla** [comment]
merged it for now, let's collect some feedback from alpha users and see how they like it

**Pull request merged**
